# Generated by Django 5.2.5 on 2025-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('AGENT_MARKETING', 'Agent marketing'), ('SECRETAIRE', 'Secrétaire admission'), ('GESTIONNAIRE', 'Gestionnaire'), ('DIRECTEUR', 'Directeur'), ('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant')], default=None, help_text='Rôle métier de l’utilisateur dans l’organisation', max_length=30, null=True),
        ),
    ]
