# Generated by Django 5.2.5 on 2025-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('event', 'Événement'), ('announcement', 'Annonce'), ('general', 'Actualité générale')], default='general', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='news/media/')),
                ('url', models.URLField(blank=True, help_text='Lien YouTube/Vimeo pour les vidéos externes', null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
