# Generated by Django 5.2.5 on 2025-08-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('subheadline', models.CharField(blank=True, max_length=200)),
                ('cta_primary_text', models.CharField(blank=True, max_length=40)),
                ('cta_primary_url', models.CharField(blank=True, max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=40)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200)),
                ('background', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Hero d'accueil",
                'verbose_name_plural': "Heros d'accueil",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=255, unique=True)),
                ('new_path', models.CharField(max_length=255)),
                ('permanent', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Alerte'), ('danger', 'Urgent')], default='info', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/')),
                ('site_name', models.CharField(default='ESFé Mali', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_main', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('map_embed', models.TextField(blank=True)),
                ('ga4_id', models.CharField(blank=True, max_length=30)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('named_url', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('new_tab', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fb', 'Facebook'), ('ig', 'Instagram'), ('yt', 'YouTube'), ('wa', 'WhatsApp'), ('x', 'X/Twitter'), ('ln', 'LinkedIn')], max_length=3)),
                ('url', models.URLField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.sitesettings')),
            ],
        ),
    ]
