# Generated by Django 5.2.5 on 2025-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annexe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
