# Generated by Django 5.2.5 on 2025-10-24 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('multiple_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='masters/resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='masterprogram',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='examgrade',
            name='masters_exa_exam_id_b2a2c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='semesterresult',
            name='masters_sem_enrollm_f0655e_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='masters_sub_assignm_dd7a38_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Chapitre bloqué avant validation préalable.'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='label',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='note_20',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='score_raw',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gradeaudit',
            name='context',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='rattrapage_take_max',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='moduleue',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moduleue',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='moduleue',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='semester',
            name='ects_target',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_unlocked_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='note_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score_raw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='lessondiscussion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='masters.lesson'),
        ),
        migrations.AddField(
            model_name='lessondiscussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='masters.lessondiscussion'),
        ),
        migrations.AddField(
            model_name='lessondiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='masters.lesson'),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='masters.lessonquiz'),
        ),
        migrations.AddField(
            model_name='lessonquizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='masters.lessonquizquestion'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='masters.lesson'),
        ),
    ]
