# Generated by Django 5.2.5 on 2025-09-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0003_alter_campus_options_campus_code_campus_email_and_more'),
        ('programs', '0004_program_campuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('source_page', models.CharField(default='detail', max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=64)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre / Préfère ne pas dire')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=120)),
                ('nationalite', models.CharField(blank=True, max_length=80)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('tuteur_nom', models.CharField(blank=True, max_length=120)),
                ('tuteur_tel', models.CharField(blank=True, max_length=32)),
                ('diplome', models.FileField(blank=True, null=True, upload_to='admissions/diplomes/')),
                ('releves', models.FileField(blank=True, null=True, upload_to='admissions/releves/')),
                ('cni', models.FileField(blank=True, null=True, upload_to='admissions/cni/')),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('fees_total_snapshot', models.PositiveIntegerField(default=0)),
                ('fees_first_tranche_snapshot', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('RECU', 'Reçu'), ('VALIDE', 'Validé par le staff'), ('A_COMPLETER', 'À compléter'), ('PRET_PAIEMENT', 'Prêt pour paiement'), ('PAIEMENT_OK', 'Paiement confirmé'), ('ADMIS', 'Admis / Inscrit'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='RECU', max_length=24)),
                ('auto_score', models.PositiveIntegerField(default=0)),
                ('rules_passed', models.BooleanField(default=False)),
                ('notes_admin', models.TextField(blank=True)),
                ('optin_whatsapp', models.BooleanField(default=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(blank=True, max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_assigned', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='campuses.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='admissions/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='admissions.admission')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='INITIE', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XOF', max_length=3)),
                ('tranche_label', models.CharField(default='1ere_tranche', max_length=40)),
                ('checkout_url', models.URLField(blank=True)),
                ('return_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('event_type', models.CharField(max_length=60)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('related_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admission')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
