# Generated by Django 5.2.5 on 2025-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé de la formation')),
                ('slug', models.SlugField(unique=True)),
                ('cycle', models.CharField(choices=[('PRIMAIRE', 'Cycle primaire'), ('SECONDAIRE', 'Cycle secondaire'), ('LICENCE', 'Cycle supérieur – Licence'), ('MASTER', 'Cycle supérieur – Master')], max_length=15)),
                ('duration', models.CharField(help_text='Ex: 2 ans, 1 an, 3 ans', max_length=50, verbose_name='Durée')),
                ('entry_requirement', models.CharField(help_text='Ex: DEF/BEPC/BAC/TSS/BT', max_length=120, verbose_name='Niveau requis')),
                ('diploma', models.CharField(blank=True, max_length=180, verbose_name='Diplôme obtenu')),
                ('short_description', models.TextField(blank=True, max_length=350, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('image', models.ImageField(blank=True, upload_to='programs/')),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant (Accueil)')),
                ('is_active', models.BooleanField(default=True)),
                ('inscription_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Frais d'inscription (XOF)")),
                ('tranche_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tranches')),
                ('tranche_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Montant par tranche (XOF)')),
                ('tuition_total', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Total scolarité (XOF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions', models.ManyToManyField(blank=True, related_name='programs', to='programs.session')),
            ],
            options={
                'ordering': ['cycle', 'title'],
            },
        ),
    ]
