# Generated by Django 5.2.5 on 2025-09-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_created_at_alter_program_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Niveau (ex: Licence 1, Master 2, etc.)'),
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Spécialisation / Domaine'),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_per_month',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Mensualité (XOF)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='entry_requirement',
            field=models.CharField(help_text='Ex: DEF / BEPC / BAC / TSS / BT', max_length=120, verbose_name='Niveau requis'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Formation active'),
        ),
    ]
