# Generated by Django 5.2.5 on 2025-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_alter_campus_options_campus_code_campus_email_and_more'),
        ('programs', '0003_program_level_program_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='programs', to='campuses.campus'),
        ),
    ]
